vim.opt.termguicolors = true
-- vim.opt.guicursor = ""
vim.opt.guicursor:remove({ "t:block-blinkon500-blinkoff500-TermCursor" })
vim.opt.cursorline = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.wrap = false
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.inccommand = "split"
vim.opt.updatetime = 50
-- vim.opt.timeoutlen = 350
vim.opt.scrolloff = 9
vim.opt.smartcase = true
vim.opt.hidden = true
vim.opt.signcolumn = "yes"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.laststatus = 3
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = false
vim.opt.clipboard:append({ "unnamedplus" })
